#include <stdio.h>

// Assuming randlc is defined elsewhere and its signature is
// double randlc(double *x, double a);
// This function is known to modify the value pointed to by the first argument,
// often involving internal state updates for a pseudorandom number generator.

static double power_refined( double a, int n ) {
    // Use distinct variables to represent the state carried through the loop iterations.
    double current_power; // Accumulates the result (corresponds to 'power' in original)
    double current_aj;    // The base value being squared iteratively (corresponds to 'aj' in original)
    int current_nj;       // The remaining part of the exponent being processed (corresponds to 'nj' in original)

    double rdummy; // Variable to catch the return value of randlc if not used

    // Initialize the state variables for the exponentiation process.
    current_power = 1.0; // Initialize the result accumulator
    current_nj = n;      // Initialize the exponent
    current_aj = a;      // Initialize the base

    // Perform exponentiation by squaring.
    // This loop iterates through the bits of 'n' from least significant to most significant.
    // The updates to current_power and current_aj via randlc introduce strong
    // loop-carried dependencies, making direct parallelization of this loop's iterations
    // challenging while preserving the exact numerical sequence generated by randlc.
    while (current_nj > 0) {
        // Check if the least significant bit of the current exponent (current_nj) is 1.
        // If it is, the current value of the base (current_aj) contributes to the result.
        // This step involves a call to randlc that updates 'current_power'.
        // This is a read-write dependency on 'current_power' and a read dependency on 'current_aj'.
        if( (current_nj % 2) == 1 ) {
            rdummy =  randlc( &current_power, current_aj );
        }

        // Prepare the base for the next iteration by squaring it (conceptually).
        // This step involves a call to randlc that updates 'current_aj'.
        // This is a read-write dependency on 'current_aj'.
        // The new value of current_aj will be used in the next iteration's potential
        // randlc(&current_power, current_aj) call and the next randlc(&current_aj, current_aj) call.
	rdummy = randlc( &current_aj, current_aj );

        // Move to the next bit of the exponent by integer division.
        // This is a read-write dependency on 'current_nj'.
	current_nj = current_nj / 2;
    }

    // The variable 'current_power' now holds the final computed value of a^n.
    return (current_power);
}